on:
  google_form:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.google_form.outputs.title}}
          contentSnippet: ${{on.google_form.outputs.contentSnippet}}
          link: ${{on.google_form.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
